### ISSUE TITLE
Extremely Outdated Docs & Example Plugin

### ISSUE THREAD

**Issue by Dartanman** [MinecraftMediaLibrary/EzMediaCore#99]
Howdy. I'm trying to use this library in my plugin, but the docs are extraordinarily outdated, and even the example plugin - DeluxeMediaPlugin - makes use of classes and methods that have been renamed or even removed entirely.

I appreciate the work you're doing, and I'm *very* impressed with how far it has come, but it's nearly impossible to use this without spending days or weeks trying to read through this big of a project and figure out how it all works, since the docs and example are so outdated.

**Comment by P10situo** [comment]
Pulse (the dev) has been very busy these last few months, and has not been able to work on the project. He says he will be back when he has time, and I know the plugin has a future because I saw it when it was working and it was perfect. In the Discord server you have more information.

**Comment by PulseBeat02** [comment]
Closing as I am working on the project. Documentation comes after the project itself functioning (I am rewriting some parts of it and I really recommend people to not use it at the moment).
